config/routes.rb
Rails.application.routes.draw do
  # root "creatures#index"
  root "landing#index"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"
  get "password_reset/:id", to: "users#password_reset", as: "password_reset"
  match "password_reset/:id", to: "users#reset", via: [:patch, :put]
  resources :users
  resources :sessions
  get 'landing/index'

  resources :abilities
  resources :condition_immunities
  post "creatures/search", to: "creatures#search"
  post "creatures/advanced_search", to: "creatures#search2"
  get "creatures/search", to: "creatures#advanced_search"
  resources :creatures
  resources :creature_actions
  resources :creature_sets
  resources :damage_immunities
  resources :damage_resistances
  resources :damage_vulnerabilities
  resources :languages
  resources :skills
  resources :spells

  get 'search/index'
  get 'search/search', as: 'search'
  post 'search', to: 'search#run_search'
  post 'search/advanced_search', to: 'search#advanced_search', as: 'advanced_search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/damage_immunity.rb
class DamageImmunity < ApplicationRecord
  has_and_belongs_to_many :creatures

  validates :name, presence: true, uniqueness: true
end

app/controllers/damage_immunities_controller.rb
class DamageImmunitiesController < ApplicationController
  before_action :set_damage_immunity, only: [:show, :edit, :update, :destroy]
  before_action :is_admin, only: [:edit, :update, :destroy]

  # GET /damage_immunities
  # GET /damage_immunities.json
  def index
    @damage_immunities = DamageImmunity.all
  end

  # GET /damage_immunities/1
  # GET /damage_immunities/1.json
  def show
  end

  # GET /damage_immunities/new
  def new
    @damage_immunity = DamageImmunity.new
  end

  # GET /damage_immunities/1/edit
  def edit
  end

  # POST /damage_immunities
  # POST /damage_immunities.json
  def create
    @damage_immunity = DamageImmunity.new(damage_immunity_params)

    respond_to do |format|
      if @damage_immunity.save
        format.html { redirect_to @damage_immunity, notice: 'Damage immunity was successfully created.' }
        format.json { render :show, status: :created, location: @damage_immunity }
      else
        format.html { render :new }
        format.json { render json: @damage_immunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /damage_immunities/1
  # PATCH/PUT /damage_immunities/1.json
  def update
    respond_to do |format|
      if @damage_immunity.update(damage_immunity_params)
        format.html { redirect_to @damage_immunity, notice: 'Damage immunity was successfully updated.' }
        format.json { render :show, status: :ok, location: @damage_immunity }
      else
        format.html { render :edit }
        format.json { render json: @damage_immunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /damage_immunities/1
  # DELETE /damage_immunities/1.json
  def destroy
    @damage_immunity.destroy
    respond_to do |format|
      format.html { redirect_to damage_immunities_url, notice: 'Damage immunity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_damage_immunity
      @damage_immunity = DamageImmunity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def damage_immunity_params
      params.fetch(:damage_immunity).permit(:name)
    end
end

app/helpers/damage_immunities_helper.rb
module DamageImmunitiesHelper
end

app/views/damage_immunities/_form.html.erb
<%= form_with(model: damage_immunity, local: true) do |form| %>
  <% if damage_immunity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(damage_immunity.errors.count, "error") %> prohibited this damage_immunity from being saved:</h2>

      <ul>
      <% damage_immunity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/damage_immunities/edit.html.erb
<h1>Editing Damage Immunity</h1>

<%= render 'form', damage_immunity: @damage_immunity %>

<%= link_to 'Show', @damage_immunity %> |
<%= link_to 'Back', damage_immunities_path %>

app/views/damage_immunities/index.html.erb
<h1>Damage Immunities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @damage_immunities.each do |damage_immunity| %>
      <tr>
        <td><%= damage_immunity.name %></td>
        <td><%= link_to 'Show', damage_immunity %></td>
        <% if admin? %>
          <td><%= link_to 'Edit', edit_damage_immunity_path(damage_immunity) %></td>
          <td><%= link_to 'Destroy', damage_immunity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Damage Immunity', new_damage_immunity_path %>

app/views/damage_immunities/new.html.erb
<h1>New Damage Immunity</h1>

<%= render 'form', damage_immunity: @damage_immunity %>

<%= link_to 'Back', damage_immunities_path %>

app/views/damage_immunities/show.html.erb
<h2><%= @damage_immunity.name%></h2>

<%= link_to 'Edit', edit_damage_immunity_path(@damage_immunity) %> |
<%= link_to 'Back', damage_immunities_path %>