config/routes.rb
Rails.application.routes.draw do
  # root "creatures#index"
  root "landing#index"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"
  get "password_reset/:id", to: "users#password_reset", as: "password_reset"
  match "password_reset/:id", to: "users#reset", via: [:patch, :put]
  resources :users
  resources :sessions
  get 'landing/index'

  resources :abilities
  resources :condition_immunities
  post "creatures/search", to: "creatures#search"
  post "creatures/advanced_search", to: "creatures#search2"
  get "creatures/search", to: "creatures#advanced_search"
  resources :creatures
  resources :creature_actions
  resources :creature_sets
  resources :damage_immunities
  resources :damage_resistances
  resources :damage_vulnerabilities
  resources :languages
  resources :skills
  resources :spells

  get 'search/index'
  get 'search/search', as: 'search'
  post 'search', to: 'search#run_search'
  post 'search/advanced_search', to: 'search#advanced_search', as: 'advanced_search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/damage_resistance.rb
class DamageResistance < ApplicationRecord
  has_and_belongs_to_many :creatures

  validates :name, presence: true, uniqueness: true
end

app/controllers/damage_resistances_controller.rb
class DamageResistancesController < ApplicationController
  before_action :set_damage_resistance, only: [:show, :edit, :update, :destroy]
  before_action :is_admin, only: [:edit, :update, :destroy]

  # GET /damage_resistances
  # GET /damage_resistances.json
  def index
    @damage_resistances = DamageResistance.all
  end

  # GET /damage_resistances/1
  # GET /damage_resistances/1.json
  def show
  end

  # GET /damage_resistances/new
  def new
    @damage_resistance = DamageResistance.new
  end

  # GET /damage_resistances/1/edit
  def edit
  end

  # POST /damage_resistances
  # POST /damage_resistances.json
  def create
    @damage_resistance = DamageResistance.new(damage_resistance_params)

    respond_to do |format|
      if @damage_resistance.save
        format.html { redirect_to @damage_resistance, notice: 'Damage resistance was successfully created.' }
        format.json { render :show, status: :created, location: @damage_resistance }
      else
        format.html { render :new }
        format.json { render json: @damage_resistance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /damage_resistances/1
  # PATCH/PUT /damage_resistances/1.json
  def update
    respond_to do |format|
      if @damage_resistance.update(damage_resistance_params)
        format.html { redirect_to @damage_resistance, notice: 'Damage resistance was successfully updated.' }
        format.json { render :show, status: :ok, location: @damage_resistance }
      else
        format.html { render :edit }
        format.json { render json: @damage_resistance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /damage_resistances/1
  # DELETE /damage_resistances/1.json
  def destroy
    @damage_resistance.destroy
    respond_to do |format|
      format.html { redirect_to damage_resistances_url, notice: 'Damage resistance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_damage_resistance
      @damage_resistance = DamageResistance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def damage_resistance_params
      params.fetch(:damage_resistance).permit(:name)
    end
end

app/helpers/damage_resistances_helper.rb
module DamageResistancesHelper
end

app/views/damage_resistances/_form.html.erb
<%= form_with(model: damage_resistance, local: true) do |form| %>
  <% if damage_resistance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(damage_resistance.errors.count, "error") %> prohibited this damage_resistance from being saved:</h2>

      <ul>
      <% damage_resistance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/damage_resistances/edit.html.erb
<h1>Editing Damage Resistance</h1>

<%= render 'form', damage_resistance: @damage_resistance %>

<%= link_to 'Show', @damage_resistance %> |
<%= link_to 'Back', damage_resistances_path %>

app/views/damage_resistances/index.html.erb
<h1>Damage Resistances</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @damage_resistances.each do |damage_resistance| %>
      <tr>
        <td><%= damage_resistance.name %></td>
        <td><%= link_to 'Show', damage_resistance %></td>
        <% if admin? %>
          <td><%= link_to 'Edit', edit_damage_resistance_path(damage_resistance) %></td>
          <td><%= link_to 'Destroy', damage_resistance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Damage Resistance', new_damage_resistance_path %>

app/views/damage_resistances/new.html.erb
<h1>New Damage Resistance</h1>

<%= render 'form', damage_resistance: @damage_resistance %>

<%= link_to 'Back', damage_resistances_path %>

app/views/damage_resistances/show.html.erb
<h2><%= @damage_resistance.name%></h2>


<%= link_to 'Edit', edit_damage_resistance_path(@damage_resistance) %> |
<%= link_to 'Back', damage_resistances_path %>