config/routes.rb
Rails.application.routes.draw do
  # root "creatures#index"
  root "landing#index"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"
  get "password_reset/:id", to: "users#password_reset", as: "password_reset"
  match "password_reset/:id", to: "users#reset", via: [:patch, :put]
  resources :users
  resources :sessions
  get 'landing/index'

  resources :abilities
  resources :condition_immunities
  post "creatures/search", to: "creatures#search"
  post "creatures/advanced_search", to: "creatures#search2"
  get "creatures/search", to: "creatures#advanced_search"
  resources :creatures
  resources :creature_actions
  resources :creature_sets
  resources :damage_immunities
  resources :damage_resistances
  resources :damage_vulnerabilities
  resources :languages
  resources :skills
  resources :spells

  get 'search/index'
  get 'search/search', as: 'search'
  post 'search', to: 'search#run_search'
  post 'search/advanced_search', to: 'search#advanced_search', as: 'advanced_search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/creature.rb
class Creature < ApplicationRecord
  include Searchable

  trigger.before(:insert) do
    "SET NEW.name = LOWER(NEW.name);"
  end

  trigger.before(:update) do
    "SET NEW.name = LOWER(NEW.name);"
  end

  # we're not going to use this, but it conflicts with the 'type'
  # column so we need to give it another name
  self.inheritance_column = 'inheritance_type'

  has_many :creature_actions, dependent: :destroy
  has_many :skills, dependent: :destroy
  has_many :abilities, dependent: :destroy
  has_and_belongs_to_many :spells
  has_and_belongs_to_many :damage_immunities
  has_and_belongs_to_many :damage_vulnerabilities
  has_and_belongs_to_many :damage_resistances
  has_and_belongs_to_many :condition_immunities
  has_and_belongs_to_many :languages

  accepts_nested_attributes_for :creature_actions, :skills, :abilities,
    :spells, :damage_immunities, :damage_vulnerabilities, :damage_resistances,
    :condition_immunities, :languages, allow_destroy: true, reject_if: :all_blank

  #validations here, with itself
  validates :name, :type, :size, :alignment, presence: true
  validates :ac, :hp, :speed, :swim, :burrow, :climb, :fly, :strength,
    :dexterity, :constitution, :intellect, :wisdom, :charisma, :perception,
    :blindsight, :darkvision, :tremorsense, :truesight, :challenge, presence: true,
    numericality: { only_integer: true }
  validates :hp_dice, dice: { message: "Dice should be in form 1d4 + 8" }
  validates :str_saving, :dex_saving, :con_saving, :int_saving,
    :wis_saving, :chr_saving, numericality: { only_integer: true, allow_nil: true }

  enum size: [:tiny, :small, :medium, :large, :huge, :gargantuan], _prefix: :size
  enum type: [
    :abberation,
    :beast,
    :celestial,
    :construct,
    :dragon,
    :fey,
    :fiend,
    :elemental,
    :giant,
    :humanoid,
    :monstrosity,
    :ooze,
    :plant,
    :undead], _prefix: :type

    def saving_throws?
      !self.str_saving.nil? ||
        !self.dex_saving.nil? ||
        !self.con_saving.nil? ||
        !self.int_saving.nil? ||
        !self.wis_saving.nil? ||
        !self.chr_saving.nil?
    end

    def self.search(attrs)
      logger.debug "In creature search"
      super(attrs) { |key, query|
        if key === :type
          self.types[query]
        elsif key === :size
          self.sizes[query]
        else
          query
        end
      }
    end
end

app/models/creature_action.rb
class CreatureAction < ApplicationRecord
  include Searchable

  belongs_to :creature

  validates :creature, :name, :description, presence: true
  validates :damage_dice, dice: { message: "Dice should be in form 1d4 + 8" }
  validates :range, presence: true, numericality: { only_integer: true }

end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  before_action :set_creature, only: [:show, :edit, :update, :destroy]
  before_action :is_admin, only: [:edit, :update, :destroy]

  def search_config
    @search_config ||= {
      path: "/creatures/search",
      placeholder: "Search Creatures"
    }
  end

  # GET /creatures
  # GET /creatures.json
  def index
    @creatures = Creature.all
  end

  #Search
  def search
    logger.debug "[Creature] hit basic search"
    @creatures = Creature.search({name: params[:query]})
    j render :index, layout: false
  end

  # POST /creatures/advanced_search
  def search2
    logger.debug "[Creature] hit advanced search"
    @creatures = Creature.search(search_params)
    j render :index, layout: false
  end

  def advanced_search
    render :search
  end

  # GET /creatures/1
  # GET /creatures/1.json
  def show
  end

  # GET /creatures/new
  def new
    @creature = Creature.new
  end

  # GET /creatures/1/edit
  def edit
  end

  # POST /creatures
  # POST /creatures.json
  def create
    @creature = Creature.new(creature_params)

    respond_to do |format|
      if @creature.save
        format.html { redirect_to @creature, notice: 'Creature was successfully created.' }
        format.json { render :show, status: :created, location: @creature }
      else
        format.html { render :new }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creatures/1
  # PATCH/PUT /creatures/1.json
  def update
    respond_to do |format|
      if @creature.update(creature_params)
        format.html { redirect_to @creature, notice: 'Creature was successfully updated.' }
        format.json { render :show, status: :ok, location: @creature }
      else
        format.html { render :edit }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creatures/1
  # DELETE /creatures/1.json
  def destroy
    @creature.destroy
    respond_to do |format|
      format.html { redirect_to creatures_url, notice: 'Creature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creature
      @creature = Creature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creature_params
      params.require(:creature).permit(
        :name,
        :type,
        :subtype,
        :size,
        :alignment,
        :ac,
        :ac_type,
        :hp,
        :hp_dice,
        :speed,
        :swim,
        :burrow,
        :climb,
        :fly,
        :strength,
        :dexterity,
        :constitution,
        :intellect,
        :wisdom,
        :charisma,
        :str_saving,
        :dex_saving,
        :con_saving,
        :int_saving,
        :wis_saving,
        :chr_saving,
        :perception,
        :blindsight,
        :darkvision,
        :tremorsense,
        :truesight,
        :challenge,
        creature_actions_attributes: [
          :id,
          :name,
          :damage_dice,
          :description,
          :range,
          :_destroy,
        ],
        abilities_attributes: [:id, :name, :description, :_destroy],
        skills_attributes: [:id, :name, :bonus, :_destroy],
        spells_attributes: [:id, :name, :description, :level, :dice, :_destroy],
        damage_immunities_attributes: [:id, :name, :_destroy],
        damage_vulnerabilities_attributes: [:id, :name, :_destroy],
        damage_resistances_attributes: [:id, :name, :_destroy],
        condition_immunities_attributes: [:id, :name, :_destroy],
        languages_attributes: [:id, :name, :_destroy],
      )
    end
end

app/helpers/creatures_helper.rb
module CreaturesHelper
  def creature_types
    enum_to_option(Creature.types)
  end

  def creature_sizes
    enum_to_option(Creature.sizes)
  end
end

app/views/creatures/_ability_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, size: "30x5" %>
  </div>

  <%= link_to_remove_association "Remove ability", f %>
</div>

app/views/creatures/_creature.html.erb
<div class="collection-item">
  <input id="creature<%= creature.id %>-collapse" class="toggle" type="checkbox" checked>
  <label for="creature<%= creature.id %>-collapse"
         class="toggle-label container collapse-header" 
         tabindex=0>
    <h2><%= creature.name.titleize %></h2>
    <div class="push-right">
      <% if admin? %>
        <%= link_to 'Show', creature_path(creature) %> |
        <%= link_to 'Edit', edit_creature_path(creature) %> |
        <%= link_to 'Destroy', creature, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </label>
  <div class="collapse-content">
    <div class="collapse-inner collapse-singleton">
      <h3>
        <%= creature.size.humanize %>
        <% if creature.subtype? %>
          <%= creature.type.humanize %> (<%= creature.subtype %>),
        <% else %>
          <%= creature.type.humanize %>,
        <% end %>
        <%= creature.alignment %>
      </h3>
      <p>
      AC: <%= creature.ac %>
    <% if creature.ac_type? %>
      (<%= creature.ac_type %>)
    <% end %>
      </p>
      <p>HP: <%= creature.hp %> (<%= creature.hp_dice %>)</p>
      <p>Speed: <%= creature.speed %>ft.</p>
      <% if creature.swim != 0 %>
        <p>Swim: <%= creature.swim %>ft.</p>
      <% end %>
      <% if creature.burrow? %>
        <p>Burrow: <%= creature.burrow %>ft.</p>
      <% end %>
      <% if creature.climb? %>
        <p>Climb: <%= creature.climb %>ft.</p>
      <% end %>
      <% if creature.fly? %>
        <p>Fly: <%= creature.fly %>ft.</p>
      <% end %>
      <h4>Stats</h4>
      <div class="container">
        <div class="flex-5">
          <p><strong>Str</strong></p>
          <p><%= creature.strength %></p>
        </div>
        <div class="flex-5">
          <p><strong>Dex</strong></p>
          <p><%= creature.dexterity %></p>
        </div>
        <div class="flex-5">
          <p><strong>Con</strong></p>
          <p><%= creature.constitution %></p>
        </div>
        <div class="flex-5">
          <p><strong>Int</strong></p>
          <p><%= creature.intellect %></p>
        </div>
        <div class="flex-5">
          <p><strong>Wis</strong></p>
          <p><%= creature.wisdom %></p>
        </div>
        <div class="flex-5">
          <p><strong>Chr</strong></p>
          <p><%= creature.charisma %></p>
        </div>
      </div>
      <% if creature.saving_throws? %>
        <h4>Saving Throws</h4>
        <p>
        <% if !creature.str_saving.nil? %>
          Str +<%= creature.str_saving %>
        <% end %>
        <% if !creature.dex_saving.nil? %>
          Dex +<%= creature.dex_saving %>
        <% end %>
        <% if !creature.con_saving.nil? %>
          Con +<%= creature.con_saving %>
        <% end %>
        <% if !creature.int_saving.nil? %>
          Int +<%= creature.int_saving %>
        <% end %>
        <% if !creature.wis_saving.nil? %>
          Wis +<%= creature.wis_saving %>
        <% end %>
        <% if !creature.chr_saving.nil? %>
          Chr +<%= creature.chr_saving %>
        <% end %>
        </p>
      <% end %>
      <p>
      Senses: passive perception: <%= creature.perception %>
      <% if creature.blindsight? %>
        blindsight: <%= creature.blindsight %>ft.
      <% end %>
      <% if creature.darkvision? %>
        darkvision: <%= creature.darkvision %>ft.
      <% end %>
      <% if creature.tremorsense? %>
        tremorsense: <%= creature.tremorsense %>ft.
      <% end %>
      <% if creature.truesight? %>
        truesight: <%= creature.truesight %>ft.
      <% end %>
      </p>
      <p>Challenge: <%= creature.challenge %> XP</p>
      <% if !creature.creature_actions.empty? %>
        <%= render layout: "creatures/show_container", locals: { model: "actions", id: creature.id } do %>
          <% for action in creature.creature_actions do %>
            <div class="collection-item">
              <h4><%= action.name %></h4>
              <p>Damage Dice: <%= action.damage_dice %></p>
              <p>Range: <%= action.range %></p>
              <p>Description: <%= action.description %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <% if !creature.abilities.empty? %>
        <%= render layout: "creatures/show_container", locals: { model: "abilities", id: creature.id } do %>
          <% for ability in creature.abilities do %>
            <div class="collection-item">
              <h4><%= ability.name %></h4>
              <p>Description: <%= ability.description %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <% if !creature.skills.empty? %>
        <%= render layout: "creatures/show_container", locals: { model: "skills", id: creature.id } do %>
          <% for skill in creature.skills do %>
            <div class="collection-item">
              <p><%= skill.name %> +<%= skill.bonus %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <% if !creature.spells.empty? %>
        <%= render layout: "creatures/show_container", locals: { model: "spells", id: creature.id } do %>
          <% for spell in creature.spells do %>
            <div class="collection-item" >
              <h4><%= spell.name %> (level <%= spell.level %>)</h4>
              <p>Description: <%= spell.description %></p>
              <p>Dice: <%= spell.dice %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <% if !creature.languages.empty? %>
        <%= render layout: "creatures/show_container", locals: { model: "languages", id: creature.id } do %>
          <% for language in creature.languages %>
            <div class="collection-item">
              <p><%= language.name %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <% if !creature.damage_vulnerabilities.empty? %>
        <%= render layout: "creatures/show_container", locals: { model: "damage_vulnerabilities", id: creature.id } do %>
          <% for damage_vulnerability in creature.damage_vulnerabilities %>
            <div class="collection-item">
              <p><%= damage_vulnerability.name %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <% if !creature.damage_resistances.empty? %>
        <%= render layout: "creatures/show_container", locals: { model: "damage_resistances", id: creature.id } do %>
          <% for damage_resistance in creature.damage_resistances %>
            <div class="collection-item">
              <p><%= damage_resistance.name %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <% if !creature.damage_immunities.empty? %>
        <%= render layout: "creatures/show_container", locals: { model: "damage_immunities", id: creature.id } do %>
          <% for damage_immunity in creature.damage_immunities %>
            <div class="collection-item">
              <p><%= damage_immunity.name %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <% if !creature.condition_immunities.empty? %>
        <%= render layout: "creatures/show_container", locals: { model: "condition_immunities", id: creature.id } do %>
          <% for condition_immunity in creature.condition_immunities %>
            <div class="collection-item">
              <p><%= condition_immunity.name %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/creatures/_creature_action_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :damage_dice %>
    <%= f.text_field :damage_dice %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :range %>
    <%= f.number_field :range %>
  </div>

  <%= link_to_remove_association "Remove action", f %>
</div>

app/views/creatures/_damage_immunity_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, list: "damage-immunities-list" %>
  </div>

  <%= link_to_remove_association "Remove damage immunity", f %>
</div>

app/views/creatures/_damage_resistance_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, list: "damage-resistances-list" %>
  </div>
  
  <%= link_to_remove_association "Remove damage resistance", f %>
</div>

app/views/creatures/_language_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, list: "languages-list" %>
  </div>

  <%= link_to_remove_association "Remove language", f %>
</div>

app/views/creatures/_skill_fields.html.erb
<div class="nested-fields">
 <div class="field">
   <%= f.label :name %>
   <%= f.text_field :name %>
 </div>

 <div class="field">
   <%= f.label :bonus %>
   <%= f.number_field :bonus %>
 </div>

 <%= link_to_remove_association "Remove skill", f %>
</div>

app/views/creatures/edit.html.erb
<h1>Editing Creature</h1>

<%= render 'form', creature: @creature, new?: false %>

<%= link_to 'Show', @creature %> |
<%= link_to 'Back', creatures_path %>

app/views/creatures/new.html.erb
<h1>New Creature</h1>

<%= render 'form', creature: @creature, new?: true %>

<%= link_to 'Back', creatures_path %>

app/views/creatures/search.html.erb
<h2> Advanced Creature Search </h2>

<%= form_with(url: "advanced_search") do |form| %>

<div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
</div>

<div class="field">
    <%= form.label :type %>
    <%= form.select :type, creature_types, { include_blank: true } %>
</div>

<div class="field">
    <%= form.label :subtype %>
    <%= form.text_field :subtype %>
</div>

<div class="field">
    <%= form.label :size %>
    <%= form.select :size, creature_sizes, { include_blank: true } %>
</div>

<div class="field">
    <%= form.label :alignment %>
    <%= form.text_field :alignment %>
</div>

<div class="field">
    <%= form.label :ac %>
    <%= form.text_field :ac %>
</div>

<div class="field">
    <%= form.label :ac_type %>
    <%= form.text_field :ac_type %>
</div>

<div class="field">
    <%= form.label :hp %>
    <%= form.number_field :hp %>
</div>

<div class="field">
    <%= form.label :hp_dice %>
    <%= form.text_field :hp_dice %>
</div>


<h3>Speed</h3>

  <div class="fields-horizontal">
    <div class="field-item flex-10">
      <%= form.label :speed %>
      <%= form.number_field :speed %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :swim %>
      <%= form.number_field :swim %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :burrow %>
      <%= form.number_field :burrow %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :climb %>
      <%= form.number_field :climb %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :fly %>
      <%= form.number_field :fly %>
    </div>
  </div>

  <h3>Stats</h3>

  <div class="fields-horizontal">
    <div class="field-item flex-10">
      <%= form.label :strength %>
      <%= form.number_field :strength %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :dexterity %>
      <%= form.number_field :dexterity %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :constitution %>
      <%= form.number_field :constitution %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :intellect %>
      <%= form.number_field :intellect %>
    </div>

    <div class="field-item flex-10">
      <%= form.label :wisdom %>
      <%= form.number_field :wisdom %>
    </div>

    <div class="field-item flex-10">
      <%= form.label :charisma %>
      <%= form.number_field :charisma %>
    </div>
  </div>

  <h3>Saving Throws</h3>

  <div class="fields-horizontal">
    <div class="field-item flex-10">
      <%= form.label :str_saving %>
      <%= form.number_field :str_saving %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :dex_saving %>
      <%= form.number_field :dex_saving %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :con_saving %>
      <%= form.number_field :con_saving %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :int_saving %>
      <%= form.number_field :int_saving %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :wis_saving %>
      <%= form.number_field :wis_saving %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :chr_saving %>
      <%= form.number_field :chr_saving %>
    </div>
  </div>

  <h3>Senses</h3>

  <div class="fields-horizontal">
    <div class="field-item flex-10">
      <%= form.label :perception %>
      <%= form.number_field :perception %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :blindsight %>
      <%= form.number_field :blindsight %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :darkvision %>
      <%= form.number_field :darkvision %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :tremorsense %>
      <%= form.number_field :tremorsense %>
    </div>
    <div class="field-item flex-10">
      <%= form.label :truesight %>
      <%= form.number_field :truesight %>
    </div>
  </div>

  <div class="field">
    <%= form.label :challenge %>
    <%= form.number_field :challenge %>
  </div>

<div class="actions">
    <%= form.submit "Search" %>
</div>

<%= link_to "Back", creatures_path %>

<% end %>

app/views/creatures/show.html.erb
<h2><%= @creature.name.titleize %></h2>
<h3>
  <%= @creature.size.humanize %>
  <% if @creature.subtype? %>
    <%= @creature.type.humanize %> (<%= @creature.subtype %>),
  <% else %>
    <%= @creature.type.humanize %>,
  <% end %>
  <%= @creature.alignment %>
</h3>
<p>
  AC: <%= @creature.ac %>
  <% if @creature.ac_type? %>
    (<%= @creature.ac_type %>)
  <% end %>
</p>
<p>HP: <%= @creature.hp %> (<%= @creature.hp_dice %>)</p>
<p>Speed: <%= @creature.speed %>ft.</p>
<% if @creature.swim != 0 %>
  <p>Swim: <%= @creature.swim %>ft.</p>
<% end %>
<% if @creature.burrow? %>
  <p>Burrow: <%= @creature.burrow %>ft.</p>
<% end %>
<% if @creature.climb? %>
  <p>Climb: <%= @creature.climb %>ft.</p>
<% end %>
<% if @creature.fly? %>
  <p>Fly: <%= @creature.fly %>ft.</p>
<% end %>
<h4>Stats</h4>
<div class="container">
  <div class="flex-5">
    <p><strong>Str</strong></p>
    <p><%= @creature.strength %></p>
  </div>
  <div class="flex-5">
    <p><strong>Dex</strong></p>
    <p><%= @creature.dexterity %></p>
  </div>
  <div class="flex-5">
    <p><strong>Con</strong></p>
    <p><%= @creature.constitution %></p>
  </div>
  <div class="flex-5">
    <p><strong>Int</strong></p>
    <p><%= @creature.intellect %></p>
  </div>
  <div class="flex-5">
    <p><strong>Wis</strong></p>
    <p><%= @creature.wisdom %></p>
  </div>
  <div class="flex-5">
    <p><strong>Chr</strong></p>
    <p><%= @creature.charisma %></p>
  </div>
</div>
<% if @creature.saving_throws? %>
<h4>Saving Throws</h4>
<p>
  <% if !@creature.str_saving.nil? %>
    Str +<%= @creature.str_saving %>
  <% end %>
  <% if !@creature.dex_saving.nil? %>
    Dex +<%= @creature.dex_saving %>
  <% end %>
  <% if !@creature.con_saving.nil? %>
    Con +<%= @creature.con_saving %>
  <% end %>
  <% if !@creature.int_saving.nil? %>
    Int +<%= @creature.int_saving %>
  <% end %>
  <% if !@creature.wis_saving.nil? %>
    Wis +<%= @creature.wis_saving %>
  <% end %>
  <% if !@creature.chr_saving.nil? %>
    Chr +<%= @creature.chr_saving %>
  <% end %>
</p>
<% end %>
<p>
  Senses: passive perception: <%= @creature.perception %>
  <% if @creature.blindsight? %>
    blindsight: <%= @creature.blindsight %>ft.
  <% end %>
  <% if @creature.darkvision? %>
    darkvision: <%= @creature.darkvision %>ft.
  <% end %>
  <% if @creature.tremorsense? %>
    tremorsense: <%= @creature.tremorsense %>ft.
  <% end %>
  <% if @creature.truesight? %>
    truesight: <%= @creature.truesight %>ft.
  <% end %>
</p>
<p>Challenge: <%= @creature.challenge %> XP</p>
<% if !@creature.creature_actions.empty? %>
  <%= render layout: "show_container", locals: { model: "actions", id: @creature.id } do %>
    <% for action in @creature.creature_actions do %>
      <div class="collection-item">
        <h4><%= action.name %></h4>
        <p>Damage Dice: <%= action.damage_dice %></p>
        <p>Range: <%= action.range %></p>
        <p>Description: <%= action.description %></p>
      </div>
    <% end %>
  <% end %>
<% end %>
<% if !@creature.abilities.empty? %>
  <%= render layout: "show_container", locals: { model: "abilities", id: @creature.id } do %>
    <% for ability in @creature.abilities do %>
      <div class="collection-item">
        <h4><%= ability.name %></h4>
        <p>Description: <%= ability.description %></p>
      </div>
    <% end %>
  <% end %>
<% end %>
<% if !@creature.skills.empty? %>
  <%= render layout: "show_container", locals: { model: "skills", id: @creature.id } do %>
    <% for skill in @creature.skills do %>
      <div class="collection-item">
        <p><%= skill.name %> +<%= skill.bonus %></p>
      </div>
    <% end %>
  <% end %>
<% end %>
<% if !@creature.spells.empty? %>
  <%= render layout: "show_container", locals: { model: "spells", id: @creature.id } do %>
    <% for spell in @creature.spells do %>
      <div class="collection-item" >
        <h4><%= spell.name %> (level <%= spell.level %>)</h4>
        <p>Description: <%= spell.description %></p>
        <p>Dice: <%= spell.dice %></p>
      </div>
    <% end %>
  <% end %>
<% end %>
<% if !@creature.languages.empty? %>
  <%= render layout: "show_container", locals: { model: "languages", id: @creature.id } do %>
    <% for language in @creature.languages %>
      <div class="collection-item">
        <p><%= language.name %></p>
      </div>
    <% end %>
  <% end %>
<% end %>
<% if !@creature.damage_vulnerabilities.empty? %>
  <%= render layout: "show_container", locals: { model: "damage_vulnerabilities", id: @creature.id } do %>
    <% for damage_vulnerability in @creature.damage_vulnerabilities %>
      <div class="collection-item">
        <p><%= damage_vulnerability.name %></p>
      </div>
    <% end %>
  <% end %>
<% end %>
<% if !@creature.damage_resistances.empty? %>
  <%= render layout: "show_container", locals: { model: "damage_resistances", id: @creature.id } do %>
    <% for damage_resistance in @creature.damage_resistances %>
      <div class="collection-item">
        <p><%= damage_resistance.name %></p>
      </div>
    <% end %>
  <% end %>
<% end %>
<% if !@creature.damage_immunities.empty? %>
  <%= render layout: "show_container", locals: { model: "damage_immunities", id: @creature.id } do %>
    <% for damage_immunity in @creature.damage_immunities %>
      <div class="collection-item">
        <p><%= damage_immunity.name %></p>
      </div>
    <% end %>
  <% end %>
<% end %>
<% if !@creature.condition_immunities.empty? %>
  <%= render layout: "show_container", locals: { model: "condition_immunities", id: @creature.id } do %>
    <% for condition_immunity in @creature.condition_immunities %>
      <div class="collection-item">
        <p><%= condition_immunity.name %></p>
      </div>
    <% end %>
  <% end %>
<% end %>
<%= link_to 'Edit', edit_creature_path(@creature) %> |
<%= link_to 'Back', creatures_path %>