config/routes.rb
Rails.application.routes.draw do
  # root "creatures#index"
  root "landing#index"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"
  get "password_reset/:id", to: "users#password_reset", as: "password_reset"
  match "password_reset/:id", to: "users#reset", via: [:patch, :put]
  resources :users
  resources :sessions
  get 'landing/index'

  resources :abilities
  resources :condition_immunities
  post "creatures/search", to: "creatures#search"
  post "creatures/advanced_search", to: "creatures#search2"
  get "creatures/search", to: "creatures#advanced_search"
  resources :creatures
  resources :creature_actions
  resources :creature_sets
  resources :damage_immunities
  resources :damage_resistances
  resources :damage_vulnerabilities
  resources :languages
  resources :skills
  resources :spells

  get 'search/index'
  get 'search/search', as: 'search'
  post 'search', to: 'search#run_search'
  post 'search/advanced_search', to: 'search#advanced_search', as: 'advanced_search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/condition_immunity.rb
class ConditionImmunity < ApplicationRecord
  has_and_belongs_to_many :creatures

  validates :name, presence: true, uniqueness: true
  
end

app/controllers/condition_immunities_controller.rb
class ConditionImmunitiesController < ApplicationController
  before_action :set_condition_immunity, only: [:show, :edit, :update, :destroy]
  before_action :is_admin, only: [:edit, :update, :destroy]

  # GET /condition_immunities
  # GET /condition_immunities.json
  def index
    @condition_immunities = ConditionImmunity.all
  end

  # GET /condition_immunities/1
  # GET /condition_immunities/1.json
  def show
  end

  # GET /condition_immunities/new
  def new
    @condition_immunity = ConditionImmunity.new
  end

  # GET /condition_immunities/1/edit
  def edit
  end

  # POST /condition_immunities
  # POST /condition_immunities.json
  def create
    @condition_immunity = ConditionImmunity.new(condition_immunity_params)

    respond_to do |format|
      if @condition_immunity.save
        format.html { redirect_to @condition_immunity, notice: 'Condition immunity was successfully created.' }
        format.json { render :show, status: :created, location: @condition_immunity }
      else
        format.html { render :new }
        format.json { render json: @condition_immunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /condition_immunities/1
  # PATCH/PUT /condition_immunities/1.json
  def update
    respond_to do |format|
      if @condition_immunity.update(condition_immunity_params)
        format.html { redirect_to @condition_immunity, notice: 'Condition immunity was successfully updated.' }
        format.json { render :show, status: :ok, location: @condition_immunity }
      else
        format.html { render :edit }
        format.json { render json: @condition_immunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /condition_immunities/1
  # DELETE /condition_immunities/1.json
  def destroy
    @condition_immunity.destroy
    respond_to do |format|
      format.html { redirect_to condition_immunities_url, notice: 'Condition immunity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condition_immunity
      @condition_immunity = ConditionImmunity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def condition_immunity_params
      params.fetch(:condition_immunity).permit(:name)
    end
end

app/helpers/condition_immunities_helper.rb
module ConditionImmunitiesHelper
end

app/views/condition_immunities/_form.html.erb
<%= form_with(model: condition_immunity, local: true) do |form| %>
  <% if condition_immunity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(condition_immunity.errors.count, "error") %> prohibited this condition_immunity from being saved:</h2>

      <ul>
      <% condition_immunity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%=form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/condition_immunities/edit.html.erb
<h1>Editing Condition Immunity</h1>

<%= render 'form', condition_immunity: @condition_immunity %>

<%= link_to 'Show', @condition_immunity %> |
<%= link_to 'Back', condition_immunities_path %>

app/views/condition_immunities/index.html.erb
<h1>Condition Immunities</h1>

<table>
  <thead>
    <tr>
      <th> Name </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @condition_immunities.each do |condition_immunity| %>
      <tr>
        <td><%= condition_immunity.name %></td>
        <td><%= link_to 'Show', condition_immunity %></td>
        <% if admin? %>
          <td><%= link_to 'Edit', edit_condition_immunity_path(condition_immunity) %></td>
          <td><%= link_to 'Destroy', condition_immunity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Condition Immunity', new_condition_immunity_path %>

app/views/condition_immunities/new.html.erb
<h1>New Condition Immunity</h1>

<%= render 'form', condition_immunity: @condition_immunity %>

<%= link_to 'Back', condition_immunities_path %>

app/views/condition_immunities/show.html.erb
<h2><%= @condition_immunity.name%></h2>

<%= link_to 'Edit', edit_condition_immunity_path(@condition_immunity) %> |
<%= link_to 'Back', condition_immunities_path %>